version: '3'

services:
  local-postgres-db:
    image: postgres:15.1-alpine3.17
    container_name: local-postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: root
    volumes:
      - database:/var/lib/postgresql/data
    ports:
      - "5433:5432"
volumes:
  database: